INSERT INTO Movie(Title, Director, Description, Duration) VALUES ('Film1', 'Director1', 'Description for film 1', 90);
INSERT INTO Movie(Title, Director, Description, Duration) VALUES ('Film2', 'Director2', 'Description for film 2', 120);
INSERT INTO Movie(Title, Director, Description, Duration) VALUES ('Film3', 'Director3', 'Description for film 3', 150);

INSERT INTO Auditorium(Name) VALUES ('Auditorium1');
INSERT INTO Auditorium(Name) VALUES ('Auditorium2');
INSERT INTO Auditorium(Name) VALUES ('Auditorium3');

INSERT INTO Screening(MovieID, AuditoriumID, ScreeningStart) VALUES (1, 1, '2019-10-16 12:00:00.000');
INSERT INTO Screening(MovieID, AuditoriumID, ScreeningStart) VALUES (1, 1, '2019-10-16 15:00:00.000');

INSERT INTO Screening(MovieID, AuditoriumID, ScreeningStart) VALUES (2, 2, '2019-10-16 12:00:00.000');
INSERT INTO Screening(MovieID, AuditoriumID, ScreeningStart) VALUES (2, 2, '2019-10-16 15:00:00.000');

INSERT INTO Screening(MovieID, AuditoriumID, ScreeningStart) VALUES (3, 3, '2019-10-16 12:00:00.000');
INSERT INTO Screening(MovieID, AuditoriumID, ScreeningStart) VALUES (3, 3, '2019-10-16 15:00:00.000');

INSERT INTO Discount(DiscountCode, DiscountValue) VALUES ('1QAZ2WSX', 50);

INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,1,1);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,2,2);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,3,3);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,4,4);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,5,5);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,6,6);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,7,7);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,8,8);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,9,9);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,1,10,10);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,1,11);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,2,12);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,3,13);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,4,14);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,5,15);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,6,16);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,7,17);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,8,18);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,9,19);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,2,10,20);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,1,21);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,2,22);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,3,23);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,4,24);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,5,25);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,6,26);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,7,27);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,8,28);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,9,29);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,3,10,30);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,1,31);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,2,32);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,3,33);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,4,34);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,5,35);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,6,36);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,7,37);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,8,38);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,9,39);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,4,10,40);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,1,41);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,2,42);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,3,43);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,4,44);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,5,45);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,6,46);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,7,47);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,8,48);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,9,49);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,5,10,50);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,1,51);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,2,52);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,3,53);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,4,54);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,5,55);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,6,56);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,7,57);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,8,58);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,9,59);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,6,10,60);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,1,61);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,2,62);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,3,63);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,4,64);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,5,65);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,6,66);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,7,67);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,8,68);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,9,69);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,7,10,70);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,1,71);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,2,72);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,3,73);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,4,74);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,5,75);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,6,76);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,7,77);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,8,78);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,9,79);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,8,10,80);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,1,81);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,2,82);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,3,83);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,4,84);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,5,85);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,6,86);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,7,87);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,8,88);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,9,89);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,9,10,90);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,1,91);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,2,92);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,3,93);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,4,94);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,5,95);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,6,96);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,7,97);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,8,98);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,9,99);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,10,10,100);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,1,101);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,2,102);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,3,103);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,4,104);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,5,105);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,6,106);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,7,107);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,8,108);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,9,109);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,11,10,110);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,1,111);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,2,112);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,3,113);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,4,114);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,5,115);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,6,116);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,7,117);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,8,118);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,9,119);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (1,12,10,120);

INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,1,1);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,2,2);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,3,3);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,4,4);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,5,5);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,6,6);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,7,7);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,8,8);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,9,9);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,1,10,10);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,1,11);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,2,12);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,3,13);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,4,14);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,5,15);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,6,16);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,7,17);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,8,18);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,9,19);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,2,10,20);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,1,21);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,2,22);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,3,23);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,4,24);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,5,25);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,6,26);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,7,27);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,8,28);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,9,29);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,3,10,30);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,1,31);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,2,32);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,3,33);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,4,34);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,5,35);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,6,36);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,7,37);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,8,38);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,9,39);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,4,10,40);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,1,41);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,2,42);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,3,43);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,4,44);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,5,45);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,6,46);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,7,47);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,8,48);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,9,49);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,5,10,50);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,1,51);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,2,52);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,3,53);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,4,54);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,5,55);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,6,56);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,7,57);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,8,58);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,9,59);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,6,10,60);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,1,61);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,2,62);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,3,63);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,4,64);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,5,65);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,6,66);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,7,67);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,8,68);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,9,69);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,7,10,70);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,1,71);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,2,72);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,3,73);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,4,74);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,5,75);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,6,76);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,7,77);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,8,78);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,9,79);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,8,10,80);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,1,81);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,2,82);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,3,83);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,4,84);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,5,85);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,6,86);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,7,87);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,8,88);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,9,89);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,9,10,90);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,1,91);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,2,92);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,3,93);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,4,94);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,5,95);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,6,96);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,7,97);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,8,98);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,9,99);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,10,10,100);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,1,101);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,2,102);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,3,103);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,4,104);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,5,105);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,6,106);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,7,107);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,8,108);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,9,109);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,11,10,110);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,1,111);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,2,112);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,3,113);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,4,114);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,5,115);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,6,116);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,7,117);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,8,118);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,9,119);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (2,12,10,120);

INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,1,1);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,2,2);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,3,3);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,4,4);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,5,5);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,6,6);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,7,7);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,8,8);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,9,9);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,1,10,10);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,1,11);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,2,12);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,3,13);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,4,14);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,5,15);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,6,16);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,7,17);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,8,18);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,9,19);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,2,10,20);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,1,21);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,2,22);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,3,23);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,4,24);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,5,25);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,6,26);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,7,27);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,8,28);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,9,29);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,3,10,30);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,1,31);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,2,32);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,3,33);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,4,34);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,5,35);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,6,36);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,7,37);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,8,38);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,9,39);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,4,10,40);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,1,41);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,2,42);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,3,43);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,4,44);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,5,45);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,6,46);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,7,47);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,8,48);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,9,49);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,5,10,50);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,1,51);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,2,52);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,3,53);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,4,54);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,5,55);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,6,56);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,7,57);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,8,58);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,9,59);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,6,10,60);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,1,61);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,2,62);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,3,63);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,4,64);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,5,65);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,6,66);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,7,67);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,8,68);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,9,69);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,7,10,70);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,1,71);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,2,72);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,3,73);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,4,74);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,5,75);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,6,76);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,7,77);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,8,78);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,9,79);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,8,10,80);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,1,81);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,2,82);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,3,83);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,4,84);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,5,85);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,6,86);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,7,87);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,8,88);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,9,89);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,9,10,90);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,1,91);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,2,92);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,3,93);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,4,94);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,5,95);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,6,96);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,7,97);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,8,98);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,9,99);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,10,10,100);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,1,101);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,2,102);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,3,103);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,4,104);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,5,105);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,6,106);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,7,107);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,8,108);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,9,109);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,11,10,110);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,1,111);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,2,112);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,3,113);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,4,114);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,5,115);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,6,116);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,7,117);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,8,118);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,9,119);
INSERT INTO Seat(AuditoriumID, RowNumber, ColNumber, SeatNumber) VALUES (3,12,10,120);


INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,1);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,2);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,3);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,4);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,5);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,6);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,7);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,8);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,9);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,10);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,11);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,12);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,13);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,14);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,15);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,16);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,17);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,18);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,19);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,20);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,21);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,22);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,23);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,24);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,25);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,26);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,27);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,28);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,29);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,30);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,31);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,32);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,33);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,34);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,35);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,36);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,37);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,38);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,39);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,40);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,41);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,42);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,43);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,44);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,45);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,46);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,47);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,48);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,49);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,50);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,51);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,52);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,53);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,54);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,55);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,56);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,57);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,58);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,59);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,60);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,61);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,62);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,63);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,64);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,65);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,66);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,67);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,68);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,69);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,70);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,71);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,72);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,73);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,74);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,75);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,76);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,77);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,78);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,79);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,80);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,81);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,82);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,83);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,84);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,85);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,86);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,87);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,88);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,89);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,90);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,91);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,92);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,93);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,94);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,95);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,96);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,97);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,98);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,99);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,100);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,101);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,102);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,103);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,104);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,105);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,106);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,107);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,108);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,109);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,110);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,111);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,112);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,113);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,114);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,115);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,116);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,117);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,118);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,119);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (1,120);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,1);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,2);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,3);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,4);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,5);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,6);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,7);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,8);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,9);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,10);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,11);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,12);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,13);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,14);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,15);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,16);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,17);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,18);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,19);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,20);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,21);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,22);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,23);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,24);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,25);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,26);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,27);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,28);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,29);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,30);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,31);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,32);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,33);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,34);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,35);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,36);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,37);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,38);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,39);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,40);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,41);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,42);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,43);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,44);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,45);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,46);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,47);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,48);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,49);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,50);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,51);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,52);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,53);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,54);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,55);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,56);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,57);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,58);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,59);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,60);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,61);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,62);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,63);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,64);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,65);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,66);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,67);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,68);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,69);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,70);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,71);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,72);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,73);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,74);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,75);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,76);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,77);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,78);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,79);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,80);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,81);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,82);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,83);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,84);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,85);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,86);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,87);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,88);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,89);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,90);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,91);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,92);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,93);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,94);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,95);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,96);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,97);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,98);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,99);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,100);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,101);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,102);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,103);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,104);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,105);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,106);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,107);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,108);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,109);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,110);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,111);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,112);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,113);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,114);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,115);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,116);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,117);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,118);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,119);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (2,120);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,1);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,2);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,3);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,4);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,5);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,6);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,7);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,8);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,9);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,10);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,11);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,12);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,13);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,14);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,15);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,16);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,17);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,18);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,19);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,20);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,21);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,22);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,23);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,24);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,25);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,26);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,27);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,28);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,29);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,30);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,31);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,32);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,33);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,34);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,35);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,36);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,37);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,38);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,39);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,40);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,41);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,42);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,43);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,44);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,45);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,46);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,47);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,48);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,49);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,50);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,51);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,52);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,53);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,54);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,55);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,56);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,57);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,58);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,59);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,60);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,61);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,62);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,63);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,64);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,65);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,66);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,67);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,68);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,69);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,70);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,71);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,72);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,73);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,74);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,75);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,76);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,77);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,78);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,79);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,80);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,81);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,82);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,83);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,84);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,85);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,86);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,87);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,88);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,89);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,90);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,91);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,92);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,93);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,94);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,95);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,96);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,97);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,98);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,99);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,100);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,101);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,102);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,103);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,104);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,105);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,106);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,107);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,108);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,109);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,110);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,111);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,112);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,113);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,114);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,115);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,116);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,117);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,118);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,119);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (3,120);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,1);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,2);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,3);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,4);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,5);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,6);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,7);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,8);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,9);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,10);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,11);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,12);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,13);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,14);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,15);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,16);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,17);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,18);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,19);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,20);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,21);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,22);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,23);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,24);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,25);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,26);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,27);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,28);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,29);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,30);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,31);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,32);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,33);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,34);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,35);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,36);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,37);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,38);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,39);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,40);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,41);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,42);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,43);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,44);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,45);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,46);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,47);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,48);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,49);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,50);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,51);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,52);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,53);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,54);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,55);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,56);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,57);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,58);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,59);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,60);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,61);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,62);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,63);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,64);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,65);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,66);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,67);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,68);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,69);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,70);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,71);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,72);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,73);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,74);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,75);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,76);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,77);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,78);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,79);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,80);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,81);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,82);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,83);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,84);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,85);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,86);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,87);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,88);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,89);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,90);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,91);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,92);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,93);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,94);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,95);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,96);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,97);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,98);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,99);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,100);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,101);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,102);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,103);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,104);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,105);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,106);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,107);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,108);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,109);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,110);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,111);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,112);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,113);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,114);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,115);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,116);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,117);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,118);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,119);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (4,120);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,1);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,2);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,3);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,4);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,5);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,6);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,7);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,8);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,9);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,10);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,11);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,12);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,13);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,14);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,15);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,16);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,17);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,18);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,19);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,20);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,21);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,22);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,23);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,24);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,25);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,26);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,27);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,28);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,29);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,30);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,31);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,32);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,33);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,34);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,35);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,36);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,37);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,38);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,39);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,40);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,41);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,42);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,43);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,44);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,45);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,46);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,47);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,48);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,49);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,50);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,51);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,52);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,53);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,54);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,55);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,56);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,57);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,58);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,59);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,60);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,61);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,62);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,63);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,64);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,65);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,66);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,67);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,68);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,69);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,70);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,71);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,72);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,73);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,74);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,75);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,76);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,77);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,78);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,79);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,80);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,81);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,82);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,83);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,84);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,85);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,86);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,87);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,88);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,89);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,90);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,91);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,92);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,93);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,94);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,95);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,96);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,97);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,98);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,99);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,100);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,101);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,102);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,103);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,104);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,105);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,106);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,107);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,108);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,109);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,110);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,111);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,112);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,113);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,114);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,115);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,116);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,117);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,118);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,119);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (5,120);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,1);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,2);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,3);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,4);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,5);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,6);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,7);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,8);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,9);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,10);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,11);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,12);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,13);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,14);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,15);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,16);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,17);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,18);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,19);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,20);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,21);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,22);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,23);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,24);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,25);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,26);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,27);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,28);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,29);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,30);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,31);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,32);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,33);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,34);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,35);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,36);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,37);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,38);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,39);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,40);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,41);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,42);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,43);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,44);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,45);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,46);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,47);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,48);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,49);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,50);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,51);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,52);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,53);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,54);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,55);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,56);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,57);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,58);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,59);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,60);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,61);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,62);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,63);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,64);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,65);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,66);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,67);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,68);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,69);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,70);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,71);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,72);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,73);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,74);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,75);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,76);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,77);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,78);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,79);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,80);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,81);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,82);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,83);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,84);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,85);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,86);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,87);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,88);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,89);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,90);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,91);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,92);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,93);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,94);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,95);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,96);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,97);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,98);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,99);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,100);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,101);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,102);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,103);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,104);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,105);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,106);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,107);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,108);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,109);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,110);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,111);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,112);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,113);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,114);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,115);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,116);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,117);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,118);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,119);
INSERT INTO ScreeningSeat(ScreeningID, SeatID) VALUES (6,120);
